services:
  postgres-commerce-dev:
    image: postgres
    container_name: postgres-commerce-dev
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      
  pgadmin-docker:
    image: dpage/pgadmin4
    container_name: pgadmin-dev
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    depends_on:
      - postgres-commerce-dev